hmc_step_config:
  step_times: [0.0, 0.25, 0.5, 0.75, 1.0]
  step_sizes: [0.5,0.35,0.25,0.075,0.05]
nuts_step_config:
  step_times: [0.0, 0.25, 0.5, 0.75, 1.0]
  step_sizes: [0.5,0.35,0.25,0.075,0.05]
nuts_steps_per_iter: 0
hmc_steps_per_iter: 1
rwm_steps_per_iter: 0
hmc_num_leapfrog_steps: 10
