hmc_step_config:
  step_times: [0.0, 0.5, 0.85, 1.0]
  step_sizes: [3.0, 1.725, 1.325, 1.225]
nuts_step_config:
  step_times: [0.0, 0.25, 0.5, 1.0]
  step_sizes: [0.5, 0.5, 0.5, 0.3]
nuts_steps_per_iter: 0
hmc_steps_per_iter: 1
rwm_steps_per_iter: 0
hmc_num_leapfrog_steps: 10
