# @package _global_

PROJECT_NAME: diffusion_smc

defaults:
  - _self_

  - server: local
  - logging: all

  - experiment: difficult_gaussian
  - method: smc
  - vi_lr_schedule: constant

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

seed: 0

steps_mult: 1

work_dir: ${hydra:runtime.cwd}
ckpt_dir: ckpt
data_dir: ${work_dir}/data
group: ${name}

mode: train
plot_train: True
eval_train: True
progress_bars: True
report_step: 1
save_samples: False

batch_size: 2000
num_smc_iters: 100
